version: "3.8"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    expose:
      - "6379"
    command: /bin/sh -c "redis-server --port 6379 --requirepass $$REDIS_HOST_PASSWORD"
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
    env_file:
      - .env

  althea-api:
    restart: unless-stopped
    build:
      context: .
    ports:
      - "3000:3000"
    env_file:
      - .env

volumes:
  redis-data:
  redis-conf:
